# Pandas

Pandas is a Python library for data analyses and manipulation. It works with tabular data (like Excel or CSV files).

This is one of the packages we installed in our environment that doesn't come with base Python.

In [1]:
import pandas as pd # import pandas with the alias `pd`

Pandas has `read` functions for a few different file formats.

In [2]:
df = pd.read_csv('../../05_src/data/slides_data/bicycle_thefts_4326.csv')

If you opened this file from your file browser, it will probably open in Excel (or an equivalent)

`df` is a pandas DataFrame object. Think of DataFrames as tables. These objects have lots of handy properties for data analysis.

In [3]:
type(df)

pandas.DataFrame

In [4]:
df.head() # show the first 5 rows of the data

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."

In [5]:
df.shape # what are the dimensions of this table?

(25569, 33)

In [6]:
df.dtypes # what are the data types of the columns in the data?

_id                        int64
OBJECTID                   int64
event_unique_id              str
Primary_Offence              str
Occurrence_Date              str
Occurrence_Year            int64
Occurrence_Month             str
Occurrence_DayOfWeek         str
Occurrence_DayOfMonth      int64
Occurrence_DayOfYear       int64
Occurrence_Hour            int64
Report_Date                  str
Report_Year                int64
Report_Month                 str
Report_DayOfWeek             str
Report_DayOfMonth          int64
Report_DayOfYear           int64
Report_Hour                int64
Division                     str
City                         str
Hood_ID                      str
NeighbourhoodName            str
Location_Type                str
Premises_Type                str
Bike_Make                    str
Bike_Model                   str
Bike_Type                    str
Bike_Speed                 int64
Bike_Colour                  str
Cost_of_Bike             float64
Status                       str
ObjectId2                  int64
geometry                     str
dtype: object

In [7]:
df.tail(3) # show the last n rows

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [8]:
# Just running `df` will show the first 5 and last 5 rows by default
df

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,25565,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01T00:00:00,2015,April,Wednesday,1,91,...,Outside,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349..."
25565,25566,11318,GO-20169004589,THEFT UNDER,2016-05-16T00:00:00,2016,May,Monday,16,137,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

We can rename any columns in our DataFrame that may not be so intuitive. 
`rename()`  takes a dictionary with the current column name as the key and the new name as the value.
This doesn't modify the DataFrame in-place, so if we want to keep it, we must reassign the result to `df` (or another variable).
Running this same code again doesn't give an error, it just doesn't do anything.

In [9]:
df = df.rename(columns = {"Cost_of_Bike": "Bike_Cost" })

In [10]:
# see a list of columns
df.columns

Index(['_id', 'OBJECTID', 'event_unique_id', 'Primary_Offence',
       'Occurrence_Date', 'Occurrence_Year', 'Occurrence_Month',
       'Occurrence_DayOfWeek', 'Occurrence_DayOfMonth', 'Occurrence_DayOfYear',
       'Occurrence_Hour', 'Report_Date', 'Report_Year', 'Report_Month',
       'Report_DayOfWeek', 'Report_DayOfMonth', 'Report_DayOfYear',
       'Report_Hour', 'Division', 'City', 'Hood_ID', 'NeighbourhoodName',
       'Location_Type', 'Premises_Type', 'Bike_Make', 'Bike_Model',
       'Bike_Type', 'Bike_Speed', 'Bike_Colour', 'Bike_Cost', 'Status',
       'ObjectId2', 'geometry'],
      dtype='str')

In [11]:
# see the unique values in a column
df["Status"].unique()

<StringArray>
['STOLEN', 'RECOVERED', 'UNKNOWN']
Length: 3, dtype: str

In [12]:
df["Status"].value_counts() # one of my favourite pandas functions!

Status
STOLEN       24807
UNKNOWN        454
RECOVERED      308
Name: count, dtype: int64

In [13]:
# overview of the dataframe: shape, columns and data types, non-null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25569 entries, 0 to 25568
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    25569 non-null  int64
 1   OBJECTID               25569 non-null  int64
 2   event_unique_id        25569 non-null  str
 3   Primary_Offence        25569 non-null  str
 4   Occurrence_Date        25569 non-null  str
 5   Occurrence_Year        25569 non-null  int64
 6   Occurrence_Month       25569 non-null  str
 7   Occurrence_DayOfWeek   25569 non-null  str
 8   Occurrence_DayOfMonth  25569 non-null  int64
 9   Occurrence_DayOfYear   25569 non-null  int64
 10  Occurrence_Hour        25569 non-null  int64
 11  Report_Date            25569 non-null  str
 12  Report_Year            25569 non-null  int64
 13  Report_Month           25569 non-null  str
 14  Report_DayOfWeek       25569 non-null  str
 15  Report_DayOfMonth      25569 non-null  int64
 16  Report_DayOfYear       25569 non-null  int64
 17  Report_Hour            25569 non-null  int64
 18  Division               25569 non-null  str
 19  City                   25569 non-null  str
 20  Hood_ID                25569 non-null  str
 21  NeighbourhoodName      25569 non-null  str
 22  Location_Type          25569 non-null  str
 23  Premises_Type          25569 non-null  str
 24  Bike_Make              25448 non-null  str
 25  Bike_Model             15923 non-null  str
 26  Bike_Type              25569 non-null  str
 27  Bike_Speed             25569 non-null  int64
 28  Bike_Colour            23508 non-null  str
 29  Bike_Cost              23825 non-null  float64
 30  Status                 25569 non-null  str
 31  ObjectId2              25569 non-null  int64
 32  geometry               25569 non-null  str
dtypes: float64(1), int64(12), str(20)
memory usage: 6.4 MB

Aside: this dataframe has a 'geometry' column, which means it is likely a spatial dataset. The package `geopandas` can be used to work with and map spatial data.

E.g.

```
import geopandas as gpd
gdf = gpd.read_file("file_path")
gdf.plot() # plots all the data on a map!
```

In [14]:
# the Occurence_Date column is supposed to have dates and times, so lets make it a 
# "datetime" data type to make it easier to work with

df["Occurrence_Date"]

0        2017-10-03T00:00:00
1        2017-11-08T00:00:00
2        2018-09-14T00:00:00
3        2015-05-07T00:00:00
4        2015-05-16T00:00:00
                ...
25564    2015-04-01T00:00:00
25565    2016-05-16T00:00:00
25566    2016-06-04T00:00:00
25567    2016-07-04T00:00:00
25568    2016-07-22T00:00:00
Name: Occurrence_Date, Length: 25569, dtype: str

In [15]:
df["Occurrence_Date"] = pd.to_datetime(df["Occurrence_Date"])

In [16]:
# Convert Status columns to category
df["Status"] = df["Status"].astype("category")

In [17]:
# summarize columns - give stats for all the columns - min, max, std, percentiles, etc.
# This summarizes only numeric columns by default, 
# passing include= all argument produces summary statistics for all the columns
df.describe(include = "all")

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Bike_Cost,Status,ObjectId2,geometry
count,25569.000000,25569.000000,25569,25569,25569,25569.000000,25569,25569,25569.000000,25569.000000,...,25569,25448,15923,25569,25569.000000,23508,23825.000000,25569,25569.000000,25569
unique,NaN,NaN,22771,66,NaN,NaN,12,7,NaN,NaN,...,7,820,8097,13,NaN,252,NaN,3,NaN,5816
top,NaN,NaN,GO-20201550944,THEFT UNDER,NaN,NaN,July,Friday,NaN,NaN,...,Outside,OT,UNKNOWN,MT,NaN,BLK,NaN,STOLEN,NaN,"{'type': 'Point', 'coordinates': (-79.38372586..."
freq,NaN,NaN,14,11904,NaN,NaN,4002,3924,NaN,NaN,...,7960,4991,304,8245,NaN,7422,NaN,24807,NaN,167
mean,12785.000000,12909.173218,NaN,NaN,2017-09-04 03:39:28.321013,2017.124174,NaN,NaN,15.616684,202.227698,...,NaN,NaN,NaN,NaN,14.164144,NaN,949.542371,NaN,12785.000000,NaN
min,1.000000,1.000000,NaN,NaN,2009-09-01 00:00:00,2009.000000,NaN,NaN,1.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,1.000000,NaN
25%,6393.000000,6456.000000,NaN,NaN,2016-01-06 00:00:00,2016.000000,NaN,NaN,8.000000,153.000000,...,NaN,NaN,NaN,NaN,6.000000,NaN,350.000000,NaN,6393.000000,NaN
50%,12785.000000,12918.000000,NaN,NaN,2017-09-05 00:00:00,2017.000000,NaN,NaN,16.000000,205.000000,...,NaN,NaN,NaN,NaN,15.000000,NaN,600.000000,NaN,12785.000000,NaN
75%,19177.000000,19360.000000,NaN,NaN,2019-06-20 00:00:00,2019.000000,NaN,NaN,23.000000,259.000000,...,NaN,NaN,NaN,NaN,21.000000,NaN,1000.000000,NaN,19177.000000,NaN
max,25569.000000,25806.000000,NaN,NaN,2020-12-30 00:00:00,2020.000000,NaN,NaN,31.000000,366.000000,...,NaN,NaN,NaN,NaN,99.000000,NaN,120000.000000,NaN,25569.000000,NaN
std,7381.278853,7448.318562,NaN,NaN,NaN,1.960127,NaN,NaN,8.592886,76.821431,...,NaN,NaN,NaN,NaN,10.559215,NaN,1675.880345,NaN,7381.278853,NaN

In pandas, most operations return a new
DataFrame by default and do not modify
the original DataFrame in place unless you
explicitly tell them to.

In [18]:
df.drop(columns = '_id') # returns the dataframe, can reassign it if desired.

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Bike_Cost,Status,ObjectId2,geometry
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,October,Tuesday,3,276,14,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,November,Wednesday,8,312,3,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,September,Friday,14,257,9,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,April,Wednesday,1,91,17,...,Outside,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349..."
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,June,Saturday,4,156,22,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,July,Monday,4,186,20,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,July,Friday,22,204,9,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [19]:
# can create new columns by just calling the new column name
df["current_year"] = 2026
df["Occurrence_Month"] = df["Occurrence_Month"].str[:3] # change to just the first 3 characters

## Filtering and selecting data

You can filter data by passing a series of true / false to use as indices. 
You can also use .loc to select by index explicitly

In [20]:
# 
df["Bike_Model"].isna() # returns a series of true / false
df.loc[df["Bike_Model"].isna()] # use that series as an index

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Bike_Cost,Status,ObjectId2,geometry,current_year
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
7,8,20993,GO-2019819460,THEFT UNDER,2019-05-01,2019,May,Wednesday,1,121,...,GARY FISHER,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
8,9,21209,GO-20179014159,THEFT UNDER,2017-09-06,2017,Sep,Wednesday,6,249,...,UK,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25561,25562,9046,GO-20149007555,THEFT UNDER,2014-10-03,2014,Oct,Friday,3,276,...,UK,NaN,RG,30,WHI,300.0,STOLEN,25562,"{'type': 'Point', 'coordinates': (-79.23001795...",2026
25562,25563,9083,GO-20143134832,THEFT UNDER,2014-10-17,2014,Oct,Friday,17,290,...,SUPERCYCLE,NaN,OT,10,YEL,NaN,STOLEN,25563,"{'type': 'Point', 'coordinates': (-79.21116678...",2026
25563,25564,9155,GO-20143239833,THEFT UNDER,2014-11-04,2014,Nov,Tuesday,4,308,...,CHEROKEE,NaN,MT,21,BLU,100.0,STOLEN,25564,"{'type': 'Point', 'coordinates': (-79.23033103...",2026
25565,25566,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,...,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,Jul,Monday,4,186,...,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026

In [21]:
df.loc[0:10] # return the row with index 0:10 
#.loc uses the actual index, #.iloc uses the position index
# careful: sometimes the index values don't match the row position

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Bike_Cost,Status,ObjectId2,geometry,current_year
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,Oct,Tuesday,3,276,...,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,Sep,Friday,14,257,...,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
5,6,18003,GO-20151861057,THEFT UNDER,2015-09-01,2015,Sep,Tuesday,1,244,...,OTHER,UNK,RC,18,TRQ,100.0,STOLEN,6,"{'type': 'Point', 'coordinates': (-79.51960669...",2026
6,7,18013,GO-20169001537,THEFT UNDER,2016-02-18,2016,Feb,Thursday,18,49,...,NO,SASQUATCH,MT,18,WHI,0.0,STOLEN,7,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
7,8,20993,GO-2019819460,THEFT UNDER,2019-05-01,2019,May,Wednesday,1,121,...,GARY FISHER,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
8,9,21209,GO-20179014159,THEFT UNDER,2017-09-06,2017,Sep,Wednesday,6,249,...,UK,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
9,10,21999,GO-20149003203,THEFT UNDER,2014-05-07,2014,May,Wednesday,7,127,...,UK,HARDROCK,MT,24,ONG,550.0,STOLEN,10,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
10,11,22015,GO-20142348560,B&E,2014-06-21,2014,Jun,Saturday,21,172,...,OTHER,NaN,RC,16,BLU,600.0,STOLEN,11,"{'type': 'Point', 'coordinates': (-79.50787435...",2026

In [22]:
# We can use the .loc[]and .isin() to filter rows in a DataFrame by providing a
# list of values for a column
models_to_keep = ["HYBRID", "SIRRUS", "ESCAPE"]

df.loc[df["Bike_Model"].isin(models_to_keep)]

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Bike_Cost,Status,ObjectId2,geometry,current_year
87,88,21080,GO-20191970007,B&E,2019-10-11,2019,Oct,Friday,11,284,...,SPECIALIZED,SIRRUS,TO,21,BLKBLU,950.0,STOLEN,87,"{'type': 'Point', 'coordinates': (-79.48640535...",2026
228,229,1135,GO-20179012278,THEFT UNDER - BICYCLE,2017-08-05,2017,Aug,Saturday,5,217,...,TR,HYBRID,OT,8,BLK,2000.0,STOLEN,224,"{'type': 'Point', 'coordinates': (-79.48678673...",2026
257,258,2748,GO-20189021105,THEFT UNDER - BICYCLE,2018-07-02,2018,Jul,Monday,2,183,...,OT,HYBRID,MT,15,WHI,1800.0,STOLEN,253,"{'type': 'Point', 'coordinates': (-79.48323001...",2026
730,731,17860,GO-20189023474,THEFT UNDER - BICYCLE,2018-07-20,2018,Jul,Friday,20,201,...,GI,ESCAPE,OT,65,GRY,650.0,STOLEN,723,"{'type': 'Point', 'coordinates': (-79.48760733...",2026
899,900,21345,GO-20181755711,B&E,2018-09-21,2018,Sep,Friday,21,264,...,SPECIALIZED,SIRRUS,OT,0,BLU,500.0,STOLEN,890,"{'type': 'Point', 'coordinates': (-79.53250412...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24346,24347,21564,GO-20201306023,THEFT UNDER - BICYCLE,2020-05-01,2020,May,Friday,1,122,...,SPECIALIZED,SIRRUS,RG,24,BLK,1300.0,STOLEN,24334,"{'type': 'Point', 'coordinates': (-79.41826195...",2026
24733,24734,1718,GO-20171919540,THEFT UNDER - BICYCLE,2017-10-17,2017,Oct,Tuesday,17,290,...,UNKNOWN MAKE,HYBRID,TO,10,BLK,700.0,UNKNOWN,24721,"{'type': 'Point', 'coordinates': (-79.23103567...",2026
24916,24917,4856,GO-20199023501,THEFT UNDER,2019-07-22,2019,Jul,Monday,22,203,...,GI,ESCAPE,OT,21,BLK,400.0,STOLEN,24904,"{'type': 'Point', 'coordinates': (-79.2826472,...",2026
24998,24999,9803,GO-20159003602,THEFT UNDER,2015-06-14,2015,Jun,Sunday,14,165,...,OT,SIRRUS,MT,18,BLK,800.0,STOLEN,24988,"{'type': 'Point', 'coordinates': (-79.26689373...",2026
25014,25015,6793,GO-20201407793,THEFT UNDER - BICYCLE,2020-06-11,2020,Jun,Thursday,11,163,...,GIANT,ESCAPE,TO,18,GRY,600.0,STOLEN,25004,"{'type': 'Point', 'coordinates': (-79.21309175...",2026

## Grouping

In [23]:
df.columns

Index(['_id', 'OBJECTID', 'event_unique_id', 'Primary_Offence',
       'Occurrence_Date', 'Occurrence_Year', 'Occurrence_Month',
       'Occurrence_DayOfWeek', 'Occurrence_DayOfMonth', 'Occurrence_DayOfYear',
       'Occurrence_Hour', 'Report_Date', 'Report_Year', 'Report_Month',
       'Report_DayOfWeek', 'Report_DayOfMonth', 'Report_DayOfYear',
       'Report_Hour', 'Division', 'City', 'Hood_ID', 'NeighbourhoodName',
       'Location_Type', 'Premises_Type', 'Bike_Make', 'Bike_Model',
       'Bike_Type', 'Bike_Speed', 'Bike_Colour', 'Bike_Cost', 'Status',
       'ObjectId2', 'geometry', 'current_year'],
      dtype='str')

In [24]:
# groupby: create groups based on a column or columns, then apply summarizations to them
df.groupby("Occurrence_DayOfWeek")['Bike_Cost'].mean()

Occurrence_DayOfWeek
Friday       952.799510
Monday       908.837284
Saturday     967.881717
Sunday       977.036629
Thursday     913.643642
Tuesday      978.617493
Wednesday    951.643933
Name: Bike_Cost, dtype: float64

In [25]:
# can group by multiple columns
# if you want the result to be its own dataframe, can use reset_index()

mean_costs_by_date = df.groupby(["Occurrence_Month", 
                                 "Occurrence_DayOfWeek"])['Bike_Cost'].mean().reset_index()

# can sort columns using sort_values
mean_costs_by_date.sort_values(by = 'Bike_Cost')

   Occurrence_Month Occurrence_DayOfWeek    Bike_Cost
36              Jul               Monday   741.718310
10              Aug               Sunday   789.532258
8               Aug               Monday   798.732510
43              Jun               Monday   809.222222
11              Aug             Thursday   816.303213
..              ...                  ...          ...
30              Jan             Saturday  1302.135135
19              Dec              Tuesday  1367.057851
1               Apr               Monday  1614.864865
34              Jan            Wednesday  1955.522727
17              Dec               Sunday  2027.781818

[84 rows x 3 columns]

In [26]:
# you can also use groupby() to create an object to iterate over

for colour, group in df.groupby("Bike_Colour"):
    # group is just a smaller dataframe with all like Bike_Colour
    print(colour, group['Bike_Cost'].mean())

18 nan
BGE 793.6285714285714
BGEBLK 700.0
BGEMRN nan
BGESIL 400.0
BGEYEL 2300.0
BLACK 2983.3333333333335
BLACK& nan
BLACVK 230.0
BLK 1029.3350682233788
BLK WH 6500.0
BLKBGE 2233.3333333333335
BLKBLU 1638.4661016949153
BLKBRN 60.0
BLKBRZ 400.0
BLKCPR 706.0
BLKDBL 3000.0
BLKDGR 937.5
BLKGLD 808.45
BLKGRN 957.7241379310345
BLKGRY 1446.5166666666667
BLKLBL 2098.5
BLKLGR 2400.0
BLKMRN 450.6666666666667
BLKMUL 2400.0
BLKONG 1262.9411764705883
BLKOTH 8250.0
BLKPLE 800.0
BLKPNK 949.6153846153846
BLKRED 1761.743842364532
BLKSIL 1063.7291666666667
BLKTAN 1800.0
BLKTRQ 1550.0
BLKWHI 2455.0454545454545
BLKYEL 1236.404255319149
BLU 748.0916590284143
BLUBLK 1369.9767441860465
BLUBRN 999.0
BLUCPR nan
BLUE nan
BLUGRN 464.1666666666667
BLUGRY 484.72222222222223
BLULBL 4000.0
BLUONG 711.1111111111111
BLUOTH nan
BLUPLE 352.5
BLUPNK 363.3333333333333
BLURED 845.7894736842105
BLUSIL 696.3478260869565
BLUTRQ 240.0
BLUTWH 300.0
BLUWHI 1469.4299065420562
BLUYEL 681.7857142857143
BRN 766.0233918128655
BRNBLK 650.0
BRNGLD 350.0
BRNMRN 2000.0
BRNONG 3000.0
BRNWHI 500.0
BRZ 654.0655737704918
BRZCPR 600.0
BRZGRN 400.0
BRZGRY 1500.0
BRZWHI 200.0
BUR 3000.0
BURGUN nan
CPR 697.4827586206897
CPRBRN 950.0
CPRGLD 500.0
CPRONG 730.0
CPRSIL 399.0
CRM 738.418918918919
CRMBLU nan
CRMWHI 175.0
DARK 600.0
DBL 695.1645569620254
DBLDGR 1370.0
DBLGRY 2486.0
DBLLBL 500.0
DBLRED 56.0
DBLSIL 600.0
DBLWHI 966.6666666666666
DBLYEL 650.0
DGR 728.804979253112
DGRBLU 175.0
DGRGLD 375.0
DGRGRY 300.0
DGRLBL nan
DGRONG 3389.0
DGRRED 679.0
DGRSIL 700.0
FRY 400.0
GLD 575.469387755102
GLDBGE 5900.0
GLDBLK 800.0
GLDBRN 475.0
GLDGRN 100.0
GLDOTH 800.0
GLDSIL 300.0
GLDWHI 500.0
GREEN 350.0
GREY nan
GRN 873.378763866878
GRNBLK 821.3913043478261
GRNBLU 449.8333333333333
GRNBRN 445.0
GRNDGR 200.0
GRNGLD 2500.0
GRNGRY 526.6666666666666
GRNLBL 190.0
GRNLGR nan
GRNMRN 900.0
GRNONG 800.0
GRNPLE 500.0
GRNPNK 4000.0
GRNRED 2325.0
GRNSIL 1266.6666666666667
GRNWHI 1039.5
GRNYEL 493.75
GRY 865.9844119036372
GRYBLK 822.7307692307693
GRYBLU 933.2307692307693
GRYBRN 2000.0
GRYGLD nan
GRYGRN 1076.076923076923
GRYLBL 2215.0
GRYLGR 600.0
GRYMUL 150.0
GRYONG 635.5882352941177
GRYOTH nan
GRYPLE 1000.0
GRYPNK 666.6666666666666
GRYRED 1844.7692307692307
GRYSIL 953.9473684210526
GRYWHI 1146.695652173913
GRYYEL 950.0
LBL 792.0838926174497
LBLDBL 2500.0
LBLGRY 700.0
LBLOTH 450.0
LBLPLE 150.0
LBLSIL 555.0
LBLWHI 200.0
LGR 784.0253164556962
LGRBLU 200.0
LGRGRY 2800.0
LGRPLE 1000.0
LGRWHI 339.0
LGRYEL 1000.0
MRN 733.2944785276073
MRNGLD 750.0
MRNGRN 440.0
MRNGRY 500.0
MRNSIL 250.0
MRNYEL 800.0
MUL 981.0
ONG 891.2522522522522
ONGBLK 4962.0
ONGBLU 800.0
ONGGRY 185.0
ONGRED 75.0
ONGSIL 1468.0
ONGTRQ 600.0
ONGWHI 1795.6666666666667
ONGYEL 1600.0
OTH 914.2038834951456
OTHRED 600.0
PLE 569.6496519721578
PLEBLK 5110.0
PLEBLU 1100.0
PLEGRN nan
PLEGRY 580.0
PLEMRN 2100.0
PLEONG 900.0
PLEPNK 350.0
PLERED 500.0
PLESIL 500.0
PLEWHI 808.8888888888889
PLEYEL 500.0
PNK 551.8770491803278
PNKBLK nan
PNKBLU 1500.0
PNKGRY 250.0
PNKPLE 967.5
PNKRED 150.0
PNKSIL 275.0
PNKTRQ 120.0
PNKWHI 190.0
PNKYEL 550.0
PURPLE nan
RED 914.1693989071039
REDBLK 1268.94
REDBLU 299.0
REDBRN 250.0
REDGLD 500.0
REDGRN 4000.0
REDGRY 212.5
REDMRN 3000.0
REDPNK 1115.0
REDSIL 841.0
REDWHI 1608.0
REDYEL 575.25
REWHI 5000.0
SIL 842.405017921147
SILBGE 800.0
SILBLK 1119.4444444444443
SILBLU 508.0
SILGRN 693.4
SILGRY 1412.5
SILLBL 510.0
SILLGR 650.0
SILONG 2100.0
SILPLE 99.5
SILPNK 330.0
SILRED 1095.8461538461538
SILVER nan
SILWHI 974.4285714285714
SILYEL 175.0
TAN 983.96
TRQ 767.8466257668712
TRQBLK 3249.5
TRQBLU 1050.0
TRQSIL nan
TRQWHI 600.0
WHI 1024.2553191489362
WHIBLK 2105.054054054054
WHIBLU 1220.2068965517242
WHIBRN 200.0
WHIGLD 1175.0
WHIGRN 1090.0
WHIGRY 2125.0
WHIONG 857.6
WHIOTH 2000.0
WHIPLE 750.0
WHIPNK 357.5
WHIRED 1791.1785714285713
WHISIL 837.5
WHIT nan
WHITE 1700.0
WHITRQ 800.0
WHIYEL 1232.2222222222222
WHT nan
YEL 833.6758409785933
YELBLK 1222.3076923076924
YELBLU 882.5
YELGRN 566.0
YELGRY 869.3333333333334
YELONG 350.0
YELOTH 500.0
YELRED 2150.0
YELSIL 320.0
YELWHI 816.6666666666666

groupby is very powerful! We have only scratched the surface. You're doing SQL next. Know that all the operations you can do in SQL - grouping, aggregating, joining data, etc. - you can do this with pandas as well.

In [27]:
# saving to file

# I like to pass index = None, otherwise you get a new index column in the saved file
mean_costs_by_date.to_csv("bike_avg_cost_by_date.csv", index = None)