In [1]:
import numpy as np

In [2]:
# list
numbers_list = [1,2,3,4,5]

#numpy array
numbers_array = np.array([1,2,3,4,5])

In [3]:
numbers_array.ndim

1

In [4]:
numbers_array.shape

(5,)

In [5]:
numbers_array.size

5

In [6]:
matrix = np.array([
[1,2,3],
[4,5,6]
])

In [7]:
matrix.ndim

2

In [8]:
matrix.shape

(2, 3)

In [9]:
matrix.size

6

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [74]:
np.random.seed(123) # keeps our random numbers reproducible
np.random.randint(1,10,5)

array([3, 3, 7, 2, 4])

In [ ]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [36]:
np.tile(numbers_array,10)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5])

In [61]:
# create a generator
rng = np.random.default_rng()
rng.normal(0,1, 10)

array([ 0.5825505 ,  1.88318075,  0.72282669, -0.06575504, -0.62756961,
       -1.34584819, -0.64703982,  0.71694336,  1.32223899,  0.04631357])

In [75]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
matrix.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [79]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6])

In [83]:
matrix1 = np.array([
    [1,2,3],
    [4,5,6]
])

matrix2 = np.array([
    [7,8,9],
    [10,11,12]
])

In [86]:
np.vstack((matrix1,matrix2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [87]:
np.hstack((matrix1,matrix2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [88]:
numbers_array

array([1, 2, 3, 4, 5])

In [89]:
numbers_array * 2

array([ 2,  4,  6,  8, 10])

In [90]:
numbers_list

[1, 2, 3, 4, 5]

In [91]:
numbers_by2 = []
for i in numbers_list:
    numbers_by2.append(i*2)

In [92]:
numbers_by2

[2, 4, 6, 8, 10]

In [93]:
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
matrix2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [95]:
matrix2 - matrix1

array([[6, 6, 6],
       [6, 6, 6]])

In [96]:
matrix1.sum()

np.int64(21)

In [97]:
matrix1.max()

np.int64(6)

In [98]:
matrix1.mean()

np.float64(3.5)

In [99]:
matrix1.mean(axis = 0)

array([2.5, 3.5, 4.5])

In [100]:
matrix.mean(axis = 1)

array([2., 5.])

In [ ]:
#matrix[row, column]
# use : say "all of"
matrix1[0,:]

array([1, 2, 3])

In [102]:
matrix1[:,1]

array([2, 5])

In [103]:
matrix1[1,1]

np.int64(5)

In [104]:
matrix3 = matrix1.copy()
matrix3

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
matrix3[1,1] = 50
matrix3

array([[ 1,  2,  3],
       [ 4, 50,  6]])

In [106]:
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
matrix3 % 3 == 0

array([[False, False,  True],
       [False, False,  True]])

In [108]:
matrix3[matrix3 % 3 == 0]

array([3, 6])

In [ ]:
np.where(matrix3 % 3 == 0 , #condition
         matrix3, # if met
         0 #else
         )

array([[0, 0, 3],
       [0, 0, 6]])

In [ ]:
# for each element in array
# if condition is met
# keep the element
# or else, replace with 0

In [112]:
q1 = np.array([[1,2,3],
               [4,5,6]])

In [ ]:
q1.shape #row, column

(2, 3)

In [113]:
arr = np.array([10,20,30,40])
arr[2]

np.int64(30)

In [114]:
arr = np.array([1,2,3])
arr * 2

array([2, 4, 6])

In [115]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [116]:
arr = np.array([1,2,3,4,5,6])
arr.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

# Exercise

In [117]:
#std = standard deviation

arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [118]:
arr.sum()

np.int64(210)

In [119]:
arr.mean()

np.float64(10.5)

In [120]:
arr.std()

np.float64(5.766281297335398)

In [121]:
arr = np.array([[2, 7, 12],
[4, 15, 3],
[8, 1, 20]])

In [122]:
# part 1
arr[arr > 10]

array([12, 15, 20])

In [123]:
# part 2
np.where(arr >= 5,
         arr,
         0)

array([[ 0,  7, 12],
       [ 0, 15,  0],
       [ 8,  0, 20]])

In [124]:
# [row, column]

#first column
arr[:,0]

array([2, 4, 8])

In [ ]:
#last row
arr[-1,:]
# or arr[2,:]

array([ 8,  1, 20])

In [126]:
#2nd row, 3rd column
arr[1,2]

np.int64(3)

In [127]:
# axis 0 = col, 1 = row
#sum of each col

arr.sum(axis = 0)

array([14, 23, 35])

In [128]:
#mean of each row
arr.mean(axis = 1)

array([7.        , 7.33333333, 9.66666667])

In [129]:
import pandas as pd

In [131]:
pd.DataFrame({
   "X": [True, False, True, True ,False],
   "Y" : [3.14, 7.65, 2.56, 7.89, 1.23],
   "Z" : ["o", "a-", "b+", "b-", "o"]
})

       X     Y   Z
0   True  3.14   o
1  False  7.65  a-
2   True  2.56  b+
3   True  7.89  b-
4  False  1.23   o

In [132]:
df = pd.read_csv("05_src/data/slides_data/bicycle_thefts_4326.csv")
df

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,25565,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01T00:00:00,2015,April,Wednesday,1,91,...,Outside,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349..."
25565,25566,11318,GO-20169004589,THEFT UNDER,2016-05-16T00:00:00,2016,May,Monday,16,137,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [133]:
df.shape

(25569, 33)

In [134]:
df.dtypes

_id                        int64
OBJECTID                   int64
event_unique_id              str
Primary_Offence              str
Occurrence_Date              str
Occurrence_Year            int64
Occurrence_Month             str
Occurrence_DayOfWeek         str
Occurrence_DayOfMonth      int64
Occurrence_DayOfYear       int64
Occurrence_Hour            int64
Report_Date                  str
Report_Year                int64
Report_Month                 str
Report_DayOfWeek             str
Report_DayOfMonth          int64
Report_DayOfYear           int64
Report_Hour                int64
Division                     str
City                         str
Hood_ID                      str
NeighbourhoodName            str
Location_Type                str
Premises_Type                str
Bike_Make                    str
Bike_Model                   str
Bike_Type                    str
Bike_Speed                 int64
Bike_Colour                  str
Cost_of_Bike             float64
Status                       str
ObjectId2                  int64
geometry                     str
dtype: object

In [135]:
df.head()

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."

In [136]:
df.tail(n = 3)

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [175]:
pd.DataFrame.rename?

Signature:
pd.DataFrame.rename(
    self,
    mapper: 'Renamer | None' = None,
    *,
    index: 'Renamer | None' = None,
    columns: 'Renamer | None' = None,
    axis: 'Axis | None' = None,
    copy: 'bool | lib.NoDefault' = <no_default>,
    inplace: 'bool' = False,
    level: 'Level | None' = None,
    errors: 'IgnoreRaise' = 'ignore',
) -> 'DataFrame | None'
Docstring:
Rename columns or index labels.

Function / dict values must be unique (1-to-1). Labels not contained in
a dict / Series will be left as-is. Extra labels listed don't throw an
error.

See the :ref:`user guide <basics.rename>` for more.

Parameters
----------
mapper : dict-like or function
    Dict-like or function transformations to apply to
    that axis' values. Use either ``mapper`` and ``axis`` to
    specify the axis to target with ``mapper``, or ``index`` and
    ``columns``.
index : dict-like or function
    Alternative to specifying axis (``mapper, axis=0``
    is equivalent to ``index=mapper``).
columns : dict-like or function
    Alternative to specifying axis (``mapper, axis=1``
    is equivalent to ``columns=mapper``).
axis : {0 or 'index', 1 or 'columns'}, default 0
    Axis to target with ``mapper``. Can be either the axis name
    ('index', 'columns') or number (0, 1). The default is 'index'.
copy : bool, default False
    This keyword is now ignored; changing its value will have no
    impact on the method.

    .. deprecated:: 3.0.0

        This keyword is ignored and will be removed in pandas 4.0. Since
        pandas 3.0, this method always returns a new object using a lazy
        copy mechanism that defers copies until necessary
        (Copy-on-Write). See the `user guide on Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        for more details.

inplace : bool, default False
    Whether to modify the DataFrame rather than creating a new one.
    If True then value of copy is ignored.
level : int or level name, default None
    In case of a MultiIndex, only rename labels in the specified
    level.
errors : {'ignore', 'raise'}, default 'ignore'
    If 'raise', raise a `KeyError` when a dict-like `mapper`, `index`,
    or `columns` contains labels that are not present in the Index
    being transformed.
    If 'ignore', existing keys will be renamed and extra keys will be
    ignored.

Returns
-------
DataFrame or None
    DataFrame with the renamed axis labels or None if ``inplace=True``.

Raises
------
KeyError
    If any of the labels is not found in the selected axis and
    "errors='raise'".

See Also
--------
DataFrame.rename_axis : Set the name of the axis.

Examples
--------
``DataFrame.rename`` supports two calling conventions

* ``(index=index_mapper, columns=columns_mapper, ...)``
* ``(mapper, axis={'index', 'columns'}, ...)``

We *highly* recommend using keyword arguments to clarify your
intent.

Rename columns using a mapping:

>>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> df.rename(columns={"A": "a", "B": "c"})
   a  c
0  1  4
1  2  5
2  3  6

Rename index using a mapping:

>>> df.rename(index={0: "x", 1: "y", 2: "z"})
   A  B
x  1  4
y  2  5
z  3  6

Cast index labels to a different type:

>>> df.index
RangeIndex(start=0, stop=3, step=1)
>>> df.rename(index=str).index
Index(['0', '1', '2'], dtype='str')

>>> df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")
Traceback (most recent call last):
KeyError: ['C'] not found in axis

Using axis-style parameters:

>>> df.rename(str.lower, axis="columns")
   a  b
0  1  4
1  2  5
2  3  6

>>> df.rename({1: 2, 2: 4}, axis="index")
   A  B
0  1  4
2  2  5
4  3  6
File:      ~/Desktop/CI:TA Positions/DSI Intro to Python/DSI_Certificate/python/python-env/lib/python3.11/site-packages/pandas/core/frame.py
Type:      function

In [138]:
# rename --> {current col name : new col name}

df = df.rename(columns = {"Cost_of_Bike" : "bike_cost"})
df

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,25565,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01T00:00:00,2015,April,Wednesday,1,91,...,Outside,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349..."
25565,25566,11318,GO-20169004589,THEFT UNDER,2016-05-16T00:00:00,2016,May,Monday,16,137,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [140]:
# df["col name"]

df["Status"].unique()

<StringArray>
['STOLEN', 'RECOVERED', 'UNKNOWN']
Length: 3, dtype: str

In [141]:
df["Status"].value_counts()

Status
STOLEN       24807
UNKNOWN        454
RECOVERED      308
Name: count, dtype: int64

In [142]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25569 entries, 0 to 25568
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    25569 non-null  int64
 1   OBJECTID               25569 non-null  int64
 2   event_unique_id        25569 non-null  str
 3   Primary_Offence        25569 non-null  str
 4   Occurrence_Date        25569 non-null  str
 5   Occurrence_Year        25569 non-null  int64
 6   Occurrence_Month       25569 non-null  str
 7   Occurrence_DayOfWeek   25569 non-null  str
 8   Occurrence_DayOfMonth  25569 non-null  int64
 9   Occurrence_DayOfYear   25569 non-null  int64
 10  Occurrence_Hour        25569 non-null  int64
 11  Report_Date            25569 non-null  str
 12  Report_Year            25569 non-null  int64
 13  Report_Month           25569 non-null  str
 14  Report_DayOfWeek       25569 non-null  str
 15  Report_DayOfMonth      25569 non-null  int64
 16  Report_DayOfYear       25569 non-null  int64
 17  Report_Hour            25569 non-null  int64
 18  Division               25569 non-null  str
 19  City                   25569 non-null  str
 20  Hood_ID                25569 non-null  str
 21  NeighbourhoodName      25569 non-null  str
 22  Location_Type          25569 non-null  str
 23  Premises_Type          25569 non-null  str
 24  Bike_Make              25448 non-null  str
 25  Bike_Model             15923 non-null  str
 26  Bike_Type              25569 non-null  str
 27  Bike_Speed             25569 non-null  int64
 28  Bike_Colour            23508 non-null  str
 29  bike_cost              23825 non-null  float64
 30  Status                 25569 non-null  str
 31  ObjectId2              25569 non-null  int64
 32  geometry               25569 non-null  str
dtypes: float64(1), int64(12), str(20)
memory usage: 6.4 MB

In [144]:
df["Occurrence_Date"] = pd.to_datetime(df["Occurrence_Date"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25569 entries, 0 to 25568
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    25569 non-null  int64
 1   OBJECTID               25569 non-null  int64
 2   event_unique_id        25569 non-null  str
 3   Primary_Offence        25569 non-null  str
 4   Occurrence_Date        25569 non-null  datetime64[us]
 5   Occurrence_Year        25569 non-null  int64
 6   Occurrence_Month       25569 non-null  str
 7   Occurrence_DayOfWeek   25569 non-null  str
 8   Occurrence_DayOfMonth  25569 non-null  int64
 9   Occurrence_DayOfYear   25569 non-null  int64
 10  Occurrence_Hour        25569 non-null  int64
 11  Report_Date            25569 non-null  str
 12  Report_Year            25569 non-null  int64
 13  Report_Month           25569 non-null  str
 14  Report_DayOfWeek       25569 non-null  str
 15  Report_DayOfMonth      25569 non-null  int64
 16  Report_DayOfYear       25569 non-null  int64
 17  Report_Hour            25569 non-null  int64
 18  Division               25569 non-null  str
 19  City                   25569 non-null  str
 20  Hood_ID                25569 non-null  str
 21  NeighbourhoodName      25569 non-null  str
 22  Location_Type          25569 non-null  str
 23  Premises_Type          25569 non-null  str
 24  Bike_Make              25448 non-null  str
 25  Bike_Model             15923 non-null  str
 26  Bike_Type              25569 non-null  str
 27  Bike_Speed             25569 non-null  int64
 28  Bike_Colour            23508 non-null  str
 29  bike_cost              23825 non-null  float64
 30  Status                 25569 non-null  str
 31  ObjectId2              25569 non-null  int64
 32  geometry               25569 non-null  str
dtypes: datetime64[us](1), float64(1), int64(12), str(19)
memory usage: 6.4 MB

In [147]:
df["Status"] = df["Status"].astype("category")
df["Status"]

0           STOLEN
1        RECOVERED
2           STOLEN
3           STOLEN
4           STOLEN
           ...
25564       STOLEN
25565       STOLEN
25566       STOLEN
25567       STOLEN
25568       STOLEN
Name: Status, Length: 25569, dtype: category
Categories (3, str): ['RECOVERED', 'STOLEN', 'UNKNOWN']

In [148]:
df.describe(include = "all")

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry
count,25569.000000,25569.000000,25569,25569,25569,25569.000000,25569,25569,25569.000000,25569.000000,...,25569,25448,15923,25569,25569.000000,23508,23825.000000,25569,25569.000000,25569
unique,NaN,NaN,22771,66,NaN,NaN,12,7,NaN,NaN,...,7,820,8097,13,NaN,252,NaN,3,NaN,5816
top,NaN,NaN,GO-20201550944,THEFT UNDER,NaN,NaN,July,Friday,NaN,NaN,...,Outside,OT,UNKNOWN,MT,NaN,BLK,NaN,STOLEN,NaN,"{'type': 'Point', 'coordinates': (-79.38372586..."
freq,NaN,NaN,14,11904,NaN,NaN,4002,3924,NaN,NaN,...,7960,4991,304,8245,NaN,7422,NaN,24807,NaN,167
mean,12785.000000,12909.173218,NaN,NaN,2017-09-04 03:39:28.321013,2017.124174,NaN,NaN,15.616684,202.227698,...,NaN,NaN,NaN,NaN,14.164144,NaN,949.542371,NaN,12785.000000,NaN
min,1.000000,1.000000,NaN,NaN,2009-09-01 00:00:00,2009.000000,NaN,NaN,1.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,1.000000,NaN
25%,6393.000000,6456.000000,NaN,NaN,2016-01-06 00:00:00,2016.000000,NaN,NaN,8.000000,153.000000,...,NaN,NaN,NaN,NaN,6.000000,NaN,350.000000,NaN,6393.000000,NaN
50%,12785.000000,12918.000000,NaN,NaN,2017-09-05 00:00:00,2017.000000,NaN,NaN,16.000000,205.000000,...,NaN,NaN,NaN,NaN,15.000000,NaN,600.000000,NaN,12785.000000,NaN
75%,19177.000000,19360.000000,NaN,NaN,2019-06-20 00:00:00,2019.000000,NaN,NaN,23.000000,259.000000,...,NaN,NaN,NaN,NaN,21.000000,NaN,1000.000000,NaN,19177.000000,NaN
max,25569.000000,25806.000000,NaN,NaN,2020-12-30 00:00:00,2020.000000,NaN,NaN,31.000000,366.000000,...,NaN,NaN,NaN,NaN,99.000000,NaN,120000.000000,NaN,25569.000000,NaN
std,7381.278853,7448.318562,NaN,NaN,NaN,1.960127,NaN,NaN,8.592886,76.821431,...,NaN,NaN,NaN,NaN,10.559215,NaN,1675.880345,NaN,7381.278853,NaN

In [149]:
df = df.drop(columns = "_id")
df

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,October,Tuesday,3,276,14,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,November,Wednesday,8,312,3,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,September,Friday,14,257,9,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,April,Wednesday,1,91,17,...,Outside,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349..."
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,June,Saturday,4,156,22,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,July,Monday,4,186,20,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,July,Friday,22,204,9,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [150]:
df["current_year"] = 2026
df

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry,current_year
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,October,Tuesday,3,276,14,...,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,November,Wednesday,8,312,3,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,September,Friday,14,257,9,...,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,April,Wednesday,1,91,17,...,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349...",2026
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,June,Saturday,4,156,22,...,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,...",2026
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,July,Monday,4,186,20,...,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,July,Friday,22,204,9,...,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742...",2026

In [153]:
df["Occurrence_Month_New"] = df["Occurrence_Month"].str[:3]
df

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry,current_year,Occurrence_Month_New
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,Oct,Tuesday,3,276,14,...,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026,Oct
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,3,...,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026,Nov
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,Sep,Friday,14,257,9,...,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,Sep
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,May
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026,May
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,Apr,Wednesday,1,91,17,...,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349...",2026,Apr
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026,May
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,Jun,Saturday,4,156,22,...,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,...",2026,Jun
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,Jul,Monday,4,186,20,...,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026,Jul
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,Jul,Friday,22,204,9,...,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742...",2026,Jul

In [ ]:
#filter using loc
df.loc[df["Bike_Model"].isna()]

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry,current_year,Occurrence_Month_New
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,3,...,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026,Nov
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,May
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026,May
7,20993,GO-2019819460,THEFT UNDER,2019-05-01,2019,May,Wednesday,1,121,13,...,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965...",2026,May
8,21209,GO-20179014159,THEFT UNDER,2017-09-06,2017,Sep,Wednesday,6,249,8,...,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965...",2026,Sep
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25561,9046,GO-20149007555,THEFT UNDER,2014-10-03,2014,Oct,Friday,3,276,21,...,NaN,RG,30,WHI,300.0,STOLEN,25562,"{'type': 'Point', 'coordinates': (-79.23001795...",2026,Oct
25562,9083,GO-20143134832,THEFT UNDER,2014-10-17,2014,Oct,Friday,17,290,17,...,NaN,OT,10,YEL,NaN,STOLEN,25563,"{'type': 'Point', 'coordinates': (-79.21116678...",2026,Oct
25563,9155,GO-20143239833,THEFT UNDER,2014-11-04,2014,Nov,Tuesday,4,308,19,...,NaN,MT,21,BLU,100.0,STOLEN,25564,"{'type': 'Point', 'coordinates': (-79.23033103...",2026,Nov
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026,May
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,Jul,Monday,4,186,20,...,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026,Jul

In [157]:
#filter using query method
df.query("Bike_Model.isna()")

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry,current_year,Occurrence_Month_New
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,3,...,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026,Nov
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,May
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026,May
7,20993,GO-2019819460,THEFT UNDER,2019-05-01,2019,May,Wednesday,1,121,13,...,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965...",2026,May
8,21209,GO-20179014159,THEFT UNDER,2017-09-06,2017,Sep,Wednesday,6,249,8,...,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965...",2026,Sep
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25561,9046,GO-20149007555,THEFT UNDER,2014-10-03,2014,Oct,Friday,3,276,21,...,NaN,RG,30,WHI,300.0,STOLEN,25562,"{'type': 'Point', 'coordinates': (-79.23001795...",2026,Oct
25562,9083,GO-20143134832,THEFT UNDER,2014-10-17,2014,Oct,Friday,17,290,17,...,NaN,OT,10,YEL,NaN,STOLEN,25563,"{'type': 'Point', 'coordinates': (-79.21116678...",2026,Oct
25563,9155,GO-20143239833,THEFT UNDER,2014-11-04,2014,Nov,Tuesday,4,308,19,...,NaN,MT,21,BLU,100.0,STOLEN,25564,"{'type': 'Point', 'coordinates': (-79.23033103...",2026,Nov
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026,May
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,Jul,Monday,4,186,20,...,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026,Jul

In [158]:
Models_to_keep = ["HYBRID","SIRRUS","ESCAPE"]

df.loc[df["Bike_Model"].isin(Models_to_keep)]

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry,current_year,Occurrence_Month_New
87,21080,GO-20191970007,B&E,2019-10-11,2019,Oct,Friday,11,284,22,...,SIRRUS,TO,21,BLKBLU,950.0,STOLEN,87,"{'type': 'Point', 'coordinates': (-79.48640535...",2026,Oct
228,1135,GO-20179012278,THEFT UNDER - BICYCLE,2017-08-05,2017,Aug,Saturday,5,217,23,...,HYBRID,OT,8,BLK,2000.0,STOLEN,224,"{'type': 'Point', 'coordinates': (-79.48678673...",2026,Aug
257,2748,GO-20189021105,THEFT UNDER - BICYCLE,2018-07-02,2018,Jul,Monday,2,183,12,...,HYBRID,MT,15,WHI,1800.0,STOLEN,253,"{'type': 'Point', 'coordinates': (-79.48323001...",2026,Jul
730,17860,GO-20189023474,THEFT UNDER - BICYCLE,2018-07-20,2018,Jul,Friday,20,201,1,...,ESCAPE,OT,65,GRY,650.0,STOLEN,723,"{'type': 'Point', 'coordinates': (-79.48760733...",2026,Jul
899,21345,GO-20181755711,B&E,2018-09-21,2018,Sep,Friday,21,264,1,...,SIRRUS,OT,0,BLU,500.0,STOLEN,890,"{'type': 'Point', 'coordinates': (-79.53250412...",2026,Sep
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24346,21564,GO-20201306023,THEFT UNDER - BICYCLE,2020-05-01,2020,May,Friday,1,122,0,...,SIRRUS,RG,24,BLK,1300.0,STOLEN,24334,"{'type': 'Point', 'coordinates': (-79.41826195...",2026,May
24733,1718,GO-20171919540,THEFT UNDER - BICYCLE,2017-10-17,2017,Oct,Tuesday,17,290,23,...,HYBRID,TO,10,BLK,700.0,UNKNOWN,24721,"{'type': 'Point', 'coordinates': (-79.23103567...",2026,Oct
24916,4856,GO-20199023501,THEFT UNDER,2019-07-22,2019,Jul,Monday,22,203,20,...,ESCAPE,OT,21,BLK,400.0,STOLEN,24904,"{'type': 'Point', 'coordinates': (-79.2826472,...",2026,Jul
24998,9803,GO-20159003602,THEFT UNDER,2015-06-14,2015,Jun,Sunday,14,165,8,...,SIRRUS,MT,18,BLK,800.0,STOLEN,24988,"{'type': 'Point', 'coordinates': (-79.26689373...",2026,Jun
25014,6793,GO-20201407793,THEFT UNDER - BICYCLE,2020-06-11,2020,Jun,Thursday,11,163,17,...,ESCAPE,TO,18,GRY,600.0,STOLEN,25004,"{'type': 'Point', 'coordinates': (-79.21309175...",2026,Jun

In [163]:
df["Bike_Model"] = (df["Bike_Model"]).str.replace("E","e")
df

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry,current_year,Occurrence_Month_New
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,Oct,Tuesday,3,276,14,...,eSCaPe 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026,Oct
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,3,...,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026,Nov
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,Sep,Friday,14,257,9,...,CROSSTRaIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,Sep
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,May
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026,May
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,Apr,Wednesday,1,91,17,...,BMX WILD MaN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349...",2026,Apr
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026,May
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,Jun,Saturday,4,156,22,...,aNTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,...",2026,Jun
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,Jul,Monday,4,186,20,...,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026,Jul
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,Jul,Friday,22,204,9,...,aSCeNT MOUNTaIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742...",2026,Jul

In [164]:
Model_Groups = df.groupby("Bike_Model")

In [165]:
Model_Groups["Bike_Make"].unique()

Bike_Model
#199-2763-0                  [SU]
&BaCK SaDDLeBaG              [GI]
'11 7.2 FX WSD               [TR]
'INTeNSe""         [UNKNOWN MAKE]
'PIRaNHa'                    [GF]
                        ...
eaSY BOaRDING                [UK]
eaSY MOTION eVO           [OTHER]
eaSY RIDe                    [OT]
eaSY RIDeR                   [UK]
eaZYRIDeRS                   [UK]
Name: Bike_Make, Length: 8097, dtype: object

In [166]:
df.to_csv("updated_df.csv")

In [177]:
df

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry,current_year,Occurrence_Month_New
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,Oct,Tuesday,3,276,14,...,eSCaPe 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026,Oct
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,Nov,Wednesday,8,312,3,...,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026,Nov
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,Sep,Friday,14,257,9,...,CROSSTRaIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,Sep
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,May
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026,May
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,Apr,Wednesday,1,91,17,...,BMX WILD MaN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349...",2026,Apr
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026,May
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,Jun,Saturday,4,156,22,...,aNTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,...",2026,Jun
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,Jul,Monday,4,186,20,...,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026,Jul
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,Jul,Friday,22,204,9,...,aSCeNT MOUNTaIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742...",2026,Jul

In [176]:
df.dropna()

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,bike_cost,Status,ObjectId2,geometry,current_year,Occurrence_Month_New
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,Oct,Tuesday,3,276,14,...,eSCaPe 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026,Oct
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,Sep,Friday,14,257,9,...,CROSSTRaIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,Sep
5,18003,GO-20151861057,THEFT UNDER,2015-09-01,2015,Sep,Tuesday,1,244,0,...,UNK,RC,18,TRQ,100.0,STOLEN,6,"{'type': 'Point', 'coordinates': (-79.51960669...",2026,Sep
6,18013,GO-20169001537,THEFT UNDER,2016-02-18,2016,Feb,Thursday,18,49,9,...,SaSQUaTCH,MT,18,WHI,0.0,STOLEN,7,"{'type': 'Point', 'coordinates': (-79.51170915...",2026,Feb
9,21999,GO-20149003203,THEFT UNDER,2014-05-07,2014,May,Wednesday,7,127,18,...,HaRDROCK,MT,24,ONG,550.0,STOLEN,10,"{'type': 'Point', 'coordinates': (-79.51132657...",2026,May
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25558,5787,GO-20199042024,THEFT UNDER,2019-12-24,2019,Dec,Tuesday,24,358,13,...,aLPHa 29,MT,21,BLK,300.0,STOLEN,25557,"{'type': 'Point', 'coordinates': (-79.22088214...",2026,Dec
25559,6471,GO-20209016189,THEFT UNDER,2020-06-03,2020,Jun,Wednesday,3,155,15,...,MOVeLO aLGONQUI,MT,10,RED,110.0,STOLEN,25558,"{'type': 'Point', 'coordinates': (-79.20060719...",2026,Jun
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,Apr,Wednesday,1,91,17,...,BMX WILD MaN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349...",2026,Apr
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,Jun,Saturday,4,156,22,...,aNTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,...",2026,Jun
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,Jul,Friday,22,204,9,...,aSCeNT MOUNTaIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742...",2026,Jul

# Exercise

In [178]:
df = pd.read_csv("05_src/data/slides_data/subway_stations.csv")
df

     stop_lat   stop_lon             station
0   43.666061 -79.411065    BATHURST STATION
1   43.670149 -79.390089         BAY STATION
2   43.766872 -79.386703     BAYVIEW STATION
3   43.769202 -79.376312   BESSARION STATION
4   43.670049 -79.385389       BLOOR STATION
..        ...        ...                 ...
72  43.734475 -79.450920      WILSON STATION
73  43.686440 -79.312471    WOODBINE STATION
74  43.670997 -79.385956       YONGE STATION
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

[77 rows x 3 columns]

In [179]:
df.head()

    stop_lat   stop_lon            station
0  43.666061 -79.411065   BATHURST STATION
1  43.670149 -79.390089        BAY STATION
2  43.766872 -79.386703    BAYVIEW STATION
3  43.769202 -79.376312  BESSARION STATION
4  43.670049 -79.385389      BLOOR STATION

In [180]:
df.tail(n = 2)

     stop_lat   stop_lon             station
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

In [181]:
df.shape

(77, 3)

In [182]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   stop_lat  77 non-null     float64
 1   stop_lon  77 non-null     float64
 2   station   77 non-null     str
dtypes: float64(2), str(1)
memory usage: 1.9 KB

In [185]:
Stations_to_keep = ["COLLEGE STATION", "ROYAL YORK STATION"]
filtered_df = df.loc[df["station"].isin(Stations_to_keep)]

In [186]:
df

     stop_lat   stop_lon             station
0   43.666061 -79.411065    BATHURST STATION
1   43.670149 -79.390089         BAY STATION
2   43.766872 -79.386703     BAYVIEW STATION
3   43.769202 -79.376312   BESSARION STATION
4   43.670049 -79.385389       BLOOR STATION
..        ...        ...                 ...
72  43.734475 -79.450920      WILSON STATION
73  43.686440 -79.312471    WOODBINE STATION
74  43.670997 -79.385956       YONGE STATION
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

[77 rows x 3 columns]

In [187]:
filtered_df

     stop_lat   stop_lon             station
9   43.660149 -79.382688     COLLEGE STATION
54  43.648338 -79.511178  ROYAL YORK STATION

In [188]:
filtered_df.to_csv("exported_data.csv")