In [1]:
import numpy as np

In [2]:
numbers_list = [1,2,3,4,5]
numbers_list

[1, 2, 3, 4, 5]

In [3]:
numbers_array = np.array([1,2,3,4,5])
numbers_array

array([1, 2, 3, 4, 5])

In [4]:
vector = np.array([1,2,3,4,5])

In [ ]:
vector.ndim #number of dimensions

1

In [ ]:
vector.size #number of values

5

In [8]:
vector.shape #size in each dimension

(5,)

In [10]:
matrix = np.array([[1,2,3],
                  [4,5,6]])

In [11]:
matrix.ndim

2

In [12]:
matrix.size

6

In [ ]:
matrix.shape # rows, columns

(2, 3)

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.random.seed(1234)
np.random.randint(1,10,5)

array([4, 7, 6, 5, 9])

In [46]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [47]:
np.tile(vector,2)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [49]:
rng = np.random.default_rng()

In [ ]:
rng.normal(0,1,10) #normal distribution

array([ 0.51898467,  0.91944108,  1.05425415,  0.44651826,  0.03992046,
        1.63969943, -0.69254302, -1.18897187, -0.90271133,  0.23480238])

In [51]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
matrix.reshape(6,1) #6 rows, 1 col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [54]:
matrix.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [55]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6])

In [57]:
matrix1 = np.array([[1,2,3],
                     [4,5,6]])

matrix2 = np.array([[7,8,9],
                   [10,11,12]])

In [58]:
np.vstack((matrix1, matrix2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
np.hstack((matrix1, matrix2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [60]:
numbers_list

[1, 2, 3, 4, 5]

In [61]:
for nums in numbers_list:
    print(nums * 2)

2
4
6
8
10

In [62]:
numbers_array

array([1, 2, 3, 4, 5])

In [65]:
numbers_array + 2

array([3, 4, 5, 6, 7])

In [66]:
matrix2 - matrix1

array([[6, 6, 6],
       [6, 6, 6]])

In [67]:
matrix1.sum()

np.int64(21)

In [68]:
matrix.max()

np.int64(12)

In [69]:
matrix1.mean()

np.float64(3.5)

In [70]:
# axis 0 = columns
# axis 1 = rows

matrix1.mean(axis = 0)

array([2.5, 3.5, 4.5])

In [71]:
matrix1.mean(axis = 1)

array([2., 5.])

In [73]:
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
len(matrix1)

2

In [75]:
# [rows, columns]

matrix1[0,:]

array([1, 2, 3])

In [77]:
matrix1[:,1]

array([2, 5])

In [78]:
matrix1[1,1]

np.int64(5)

In [79]:
matrix3 = np.ones((2,3))
matrix3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
matrix3[1,1] = 50
matrix3

array([[ 1.,  1.,  1.],
       [ 1., 50.,  1.]])

In [81]:
matrix2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [82]:
matrix2 % 3 == 0

array([[False, False,  True],
       [False, False,  True]])

In [83]:
matrix2[matrix2 % 3 == 0]

array([ 9, 12])

In [84]:
np.where(matrix2 % 3 == 0,
         matrix2,
         0)

array([[ 0,  0,  9],
       [ 0,  0, 12]])

In [85]:
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
matrix1[matrix1 % 2 != 0]

array([1, 3, 5])

In [87]:
matrix3

array([[ 1.,  1.,  1.],
       [ 1., 50.,  1.]])

In [89]:
matrix3[0,0] = 100

In [90]:
matrix3

array([[100.,   1.,   1.],
       [  1.,  50.,   1.]])

In [91]:
numbers = [1,2,3,4,5,6]

In [92]:
empty_list = []
for num in numbers:
    if num % 2 != 0:
        empty_list.append(num)
    else:
        empty_list.append(0)

In [93]:
empty_list

[1, 0, 3, 0, 5, 0]

In [95]:
q1 = np.array([[1,2,3],
              [4,5,6]])

In [96]:
q1.shape

(2, 3)

In [97]:
q2 = np.array([10,20,30,40])
q2[2]

np.int64(30)

In [98]:
q3 = np.array([1,2,3])
q3 * 2

array([2, 4, 6])

In [99]:
q4 = np.zeros((2,3))
q4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
q5 = np.array([1,2,3,4,5,6])
q5.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

# Exercise

In [101]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [102]:
arr.sum()

np.int64(210)

In [103]:
arr.mean()

np.float64(10.5)

In [105]:
round(arr.std(),2)

np.float64(5.77)

# Exercise 2

In [107]:
arr = np.array([[2, 7, 12], 
                [4, 15, 3],
                [8, 1, 20]])

In [108]:
arr[arr > 10]

array([12, 15, 20])

In [109]:
np.where(arr >= 5,
         arr,
         0)

array([[ 0,  7, 12],
       [ 0, 15,  0],
       [ 8,  0, 20]])

In [110]:
np.where(arr < 5,
         0,
         arr)

array([[ 0,  7, 12],
       [ 0, 15,  0],
       [ 8,  0, 20]])

# Exercise 3

In [111]:
# rows, columns
arr[:,0]

array([2, 4, 8])

In [112]:
arr[2,:]

array([ 8,  1, 20])

In [113]:
arr[1,2]

np.int64(3)

# Exercise 4

In [114]:
arr.sum(axis = 0)

array([14, 23, 35])

In [115]:
arr.mean(axis = 1)

array([7.        , 7.33333333, 9.66666667])

In [116]:
import pandas as pd

In [117]:
pd.DataFrame({
    "X": [True, False, True, True, False],
    "Y": [3.14,7.65,2.56,7.89,1.23],
    "Z": ["o","a-","b+","b-","o"]
})

       X     Y   Z
0   True  3.14   o
1  False  7.65  a-
2   True  2.56  b+
3   True  7.89  b-
4  False  1.23   o

In [129]:
import os
os.getcwd()

'/Users/juliagallucci/Desktop/CI:TA Positions/DSI Intro to Python/DSI_Certificate'

In [130]:
df = pd.read_csv("python/05_src/data/slides_data/bicycle_thefts_4326.csv")
df

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,25565,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01T00:00:00,2015,April,Wednesday,1,91,...,Outside,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349..."
25565,25566,11318,GO-20169004589,THEFT UNDER,2016-05-16T00:00:00,2016,May,Monday,16,137,...,House,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046..."
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [131]:
df.shape

(25569, 33)

In [132]:
df.dtypes

_id                        int64
OBJECTID                   int64
event_unique_id           object
Primary_Offence           object
Occurrence_Date           object
Occurrence_Year            int64
Occurrence_Month          object
Occurrence_DayOfWeek      object
Occurrence_DayOfMonth      int64
Occurrence_DayOfYear       int64
Occurrence_Hour            int64
Report_Date               object
Report_Year                int64
Report_Month              object
Report_DayOfWeek          object
Report_DayOfMonth          int64
Report_DayOfYear           int64
Report_Hour                int64
Division                  object
City                      object
Hood_ID                   object
NeighbourhoodName         object
Location_Type             object
Premises_Type             object
Bike_Make                 object
Bike_Model                object
Bike_Type                 object
Bike_Speed                 int64
Bike_Colour               object
Cost_of_Bike             float64
Status                    object
ObjectId2                  int64
geometry                  object
dtype: object

In [133]:
df.head()

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
0,1,17744,GO-20179016397,THEFT UNDER,2017-10-03T00:00:00,2017,October,Tuesday,3,276,...,Outside,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965..."
1,2,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08T00:00:00,2017,November,Wednesday,8,312,...,House,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874..."
2,3,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14T00:00:00,2018,September,Friday,14,257,...,Transit,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915..."
3,4,17962,GO-2015804467,THEFT UNDER,2015-05-07T00:00:00,2015,May,Thursday,7,127,...,Transit,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915..."
4,5,17963,GO-20159002781,THEFT UNDER,2015-05-16T00:00:00,2015,May,Saturday,16,136,...,Transit,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657..."

In [134]:
df.tail(n = 3)

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
25566,25567,11462,GO-20169005434,THEFT UNDER,2016-06-04T00:00:00,2016,June,Saturday,4,156,...,Apartment,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,..."
25567,25568,11695,GO-20161170896,THEFT UNDER,2016-07-04T00:00:00,2016,July,Monday,4,186,...,Commercial,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719..."
25568,25569,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22T00:00:00,2016,July,Friday,22,204,...,Outside,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742..."

In [135]:
df = df.rename(columns= {"cost_of_bike" : "bike_cost"})

In [136]:
df["Status"]

0           STOLEN
1        RECOVERED
2           STOLEN
3           STOLEN
4           STOLEN
           ...
25564       STOLEN
25565       STOLEN
25566       STOLEN
25567       STOLEN
25568       STOLEN
Name: Status, Length: 25569, dtype: object

In [137]:
df["Status"].unique()

array(['STOLEN', 'RECOVERED', 'UNKNOWN'], dtype=object)

In [138]:
df["Status"].value_counts()

Status
STOLEN       24807
UNKNOWN        454
RECOVERED      308
Name: count, dtype: int64

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25569 entries, 0 to 25568
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    25569 non-null  int64
 1   OBJECTID               25569 non-null  int64
 2   event_unique_id        25569 non-null  object
 3   Primary_Offence        25569 non-null  object
 4   Occurrence_Date        25569 non-null  object
 5   Occurrence_Year        25569 non-null  int64
 6   Occurrence_Month       25569 non-null  object
 7   Occurrence_DayOfWeek   25569 non-null  object
 8   Occurrence_DayOfMonth  25569 non-null  int64
 9   Occurrence_DayOfYear   25569 non-null  int64
 10  Occurrence_Hour        25569 non-null  int64
 11  Report_Date            25569 non-null  object
 12  Report_Year            25569 non-null  int64
 13  Report_Month           25569 non-null  object
 14  Report_DayOfWeek       25569 non-null  object
 15  Report_DayOfMonth      25569 non-null  int64
 16  Report_DayOfYear       25569 non-null  int64
 17  Report_Hour            25569 non-null  int64
 18  Division               25569 non-null  object
 19  City                   25569 non-null  object
 20  Hood_ID                25569 non-null  object
 21  NeighbourhoodName      25569 non-null  object
 22  Location_Type          25569 non-null  object
 23  Premises_Type          25569 non-null  object
 24  Bike_Make              25448 non-null  object
 25  Bike_Model             15923 non-null  object
 26  Bike_Type              25569 non-null  object
 27  Bike_Speed             25569 non-null  int64
 28  Bike_Colour            23508 non-null  object
 29  Cost_of_Bike           23825 non-null  float64
 30  Status                 25569 non-null  object
 31  ObjectId2              25569 non-null  int64
 32  geometry               25569 non-null  object
dtypes: float64(1), int64(12), object(20)
memory usage: 6.4+ MB

In [140]:
df["Occurrence_Date"] = pd.to_datetime(df["Occurrence_Date"])

In [141]:
df["Status"] = df["Status"].astype("category")

In [143]:
df.describe(include = "all")

,_id,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,...,Premises_Type,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry
count,25569.000000,25569.000000,25569,25569,25569,25569.000000,25569,25569,25569.000000,25569.000000,...,25569,25448,15923,25569,25569.000000,23508,23825.000000,25569,25569.000000,25569
unique,NaN,NaN,22771,66,NaN,NaN,12,7,NaN,NaN,...,7,820,8097,13,NaN,252,NaN,3,NaN,5816
top,NaN,NaN,GO-20201550944,THEFT UNDER,NaN,NaN,July,Friday,NaN,NaN,...,Outside,OT,UNKNOWN,MT,NaN,BLK,NaN,STOLEN,NaN,"{'type': 'Point', 'coordinates': (-79.38372586..."
freq,NaN,NaN,14,11904,NaN,NaN,4002,3924,NaN,NaN,...,7960,4991,304,8245,NaN,7422,NaN,24807,NaN,167
mean,12785.000000,12909.173218,NaN,NaN,2017-09-04 03:39:28.321013504,2017.124174,NaN,NaN,15.616684,202.227698,...,NaN,NaN,NaN,NaN,14.164144,NaN,949.542371,NaN,12785.000000,NaN
min,1.000000,1.000000,NaN,NaN,2009-09-01 00:00:00,2009.000000,NaN,NaN,1.000000,1.000000,...,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,1.000000,NaN
25%,6393.000000,6456.000000,NaN,NaN,2016-01-06 00:00:00,2016.000000,NaN,NaN,8.000000,153.000000,...,NaN,NaN,NaN,NaN,6.000000,NaN,350.000000,NaN,6393.000000,NaN
50%,12785.000000,12918.000000,NaN,NaN,2017-09-05 00:00:00,2017.000000,NaN,NaN,16.000000,205.000000,...,NaN,NaN,NaN,NaN,15.000000,NaN,600.000000,NaN,12785.000000,NaN
75%,19177.000000,19360.000000,NaN,NaN,2019-06-20 00:00:00,2019.000000,NaN,NaN,23.000000,259.000000,...,NaN,NaN,NaN,NaN,21.000000,NaN,1000.000000,NaN,19177.000000,NaN
max,25569.000000,25806.000000,NaN,NaN,2020-12-30 00:00:00,2020.000000,NaN,NaN,31.000000,366.000000,...,NaN,NaN,NaN,NaN,99.000000,NaN,120000.000000,NaN,25569.000000,NaN
std,7381.278853,7448.318562,NaN,NaN,NaN,1.960127,NaN,NaN,8.592886,76.821431,...,NaN,NaN,NaN,NaN,10.559215,NaN,1675.880345,NaN,7381.278853,NaN

In [145]:
df = df.drop(columns="_id")

In [146]:
df["current_year"] = 2026
df

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry,current_year
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,October,Tuesday,3,276,14,...,GI,ESCAPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,November,Wednesday,8,312,3,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,September,Friday,14,257,9,...,OT,CROSSTRAIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,May,Thursday,7,127,18,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,May,Saturday,16,136,12,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,April,Wednesday,1,91,17,...,UNKNOWN MAKE,BMX WILD MAN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349...",2026
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,May,Monday,16,137,21,...,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,June,Saturday,4,156,22,...,SC,ANTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,...",2026
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,July,Monday,4,186,20,...,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,July,Friday,22,204,9,...,SU,ASCENT MOUNTAIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742...",2026

In [149]:
df["Occurrence_Month"] = df["Occurrence_Month"][:3]

In [150]:
df.loc[df["Bike_Model"].isna()]

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry,current_year
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,November,Wednesday,8,312,3,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,NaN,Thursday,7,127,18,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,NaN,Saturday,16,136,12,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
7,20993,GO-2019819460,THEFT UNDER,2019-05-01,2019,NaN,Wednesday,1,121,13,...,GARY FISHER,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
8,21209,GO-20179014159,THEFT UNDER,2017-09-06,2017,NaN,Wednesday,6,249,8,...,UK,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25561,9046,GO-20149007555,THEFT UNDER,2014-10-03,2014,NaN,Friday,3,276,21,...,UK,NaN,RG,30,WHI,300.0,STOLEN,25562,"{'type': 'Point', 'coordinates': (-79.23001795...",2026
25562,9083,GO-20143134832,THEFT UNDER,2014-10-17,2014,NaN,Friday,17,290,17,...,SUPERCYCLE,NaN,OT,10,YEL,NaN,STOLEN,25563,"{'type': 'Point', 'coordinates': (-79.21116678...",2026
25563,9155,GO-20143239833,THEFT UNDER,2014-11-04,2014,NaN,Tuesday,4,308,19,...,CHEROKEE,NaN,MT,21,BLU,100.0,STOLEN,25564,"{'type': 'Point', 'coordinates': (-79.23033103...",2026
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,NaN,Monday,16,137,21,...,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,NaN,Monday,4,186,20,...,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026

In [151]:
df.query("Bike_Model.isna()")

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry,current_year
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,November,Wednesday,8,312,3,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,NaN,Thursday,7,127,18,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,NaN,Saturday,16,136,12,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
7,20993,GO-2019819460,THEFT UNDER,2019-05-01,2019,NaN,Wednesday,1,121,13,...,GARY FISHER,NaN,OT,7,BLK,800.0,STOLEN,8,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
8,21209,GO-20179014159,THEFT UNDER,2017-09-06,2017,NaN,Wednesday,6,249,8,...,UK,NaN,RG,20,BLK,700.0,STOLEN,9,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25561,9046,GO-20149007555,THEFT UNDER,2014-10-03,2014,NaN,Friday,3,276,21,...,UK,NaN,RG,30,WHI,300.0,STOLEN,25562,"{'type': 'Point', 'coordinates': (-79.23001795...",2026
25562,9083,GO-20143134832,THEFT UNDER,2014-10-17,2014,NaN,Friday,17,290,17,...,SUPERCYCLE,NaN,OT,10,YEL,NaN,STOLEN,25563,"{'type': 'Point', 'coordinates': (-79.21116678...",2026
25563,9155,GO-20143239833,THEFT UNDER,2014-11-04,2014,NaN,Tuesday,4,308,19,...,CHEROKEE,NaN,MT,21,BLU,100.0,STOLEN,25564,"{'type': 'Point', 'coordinates': (-79.23033103...",2026
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,NaN,Monday,16,137,21,...,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,NaN,Monday,4,186,20,...,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026

In [152]:
Models_to_keep = ["HYBRID","SIRRUS","ESCAPE"]

df.loc[df["Bike_Model"].isin(Models_to_keep)]

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry,current_year
87,21080,GO-20191970007,B&E,2019-10-11,2019,NaN,Friday,11,284,22,...,SPECIALIZED,SIRRUS,TO,21,BLKBLU,950.0,STOLEN,87,"{'type': 'Point', 'coordinates': (-79.48640535...",2026
228,1135,GO-20179012278,THEFT UNDER - BICYCLE,2017-08-05,2017,NaN,Saturday,5,217,23,...,TR,HYBRID,OT,8,BLK,2000.0,STOLEN,224,"{'type': 'Point', 'coordinates': (-79.48678673...",2026
257,2748,GO-20189021105,THEFT UNDER - BICYCLE,2018-07-02,2018,NaN,Monday,2,183,12,...,OT,HYBRID,MT,15,WHI,1800.0,STOLEN,253,"{'type': 'Point', 'coordinates': (-79.48323001...",2026
730,17860,GO-20189023474,THEFT UNDER - BICYCLE,2018-07-20,2018,NaN,Friday,20,201,1,...,GI,ESCAPE,OT,65,GRY,650.0,STOLEN,723,"{'type': 'Point', 'coordinates': (-79.48760733...",2026
899,21345,GO-20181755711,B&E,2018-09-21,2018,NaN,Friday,21,264,1,...,SPECIALIZED,SIRRUS,OT,0,BLU,500.0,STOLEN,890,"{'type': 'Point', 'coordinates': (-79.53250412...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24346,21564,GO-20201306023,THEFT UNDER - BICYCLE,2020-05-01,2020,NaN,Friday,1,122,0,...,SPECIALIZED,SIRRUS,RG,24,BLK,1300.0,STOLEN,24334,"{'type': 'Point', 'coordinates': (-79.41826195...",2026
24733,1718,GO-20171919540,THEFT UNDER - BICYCLE,2017-10-17,2017,NaN,Tuesday,17,290,23,...,UNKNOWN MAKE,HYBRID,TO,10,BLK,700.0,UNKNOWN,24721,"{'type': 'Point', 'coordinates': (-79.23103567...",2026
24916,4856,GO-20199023501,THEFT UNDER,2019-07-22,2019,NaN,Monday,22,203,20,...,GI,ESCAPE,OT,21,BLK,400.0,STOLEN,24904,"{'type': 'Point', 'coordinates': (-79.2826472,...",2026
24998,9803,GO-20159003602,THEFT UNDER,2015-06-14,2015,NaN,Sunday,14,165,8,...,OT,SIRRUS,MT,18,BLK,800.0,STOLEN,24988,"{'type': 'Point', 'coordinates': (-79.26689373...",2026
25014,6793,GO-20201407793,THEFT UNDER - BICYCLE,2020-06-11,2020,NaN,Thursday,11,163,17,...,GIANT,ESCAPE,TO,18,GRY,600.0,STOLEN,25004,"{'type': 'Point', 'coordinates': (-79.21309175...",2026

In [154]:
df["Bike_Model"] = df["Bike_Model"].str.replace("A","a")
df

,OBJECTID,event_unique_id,Primary_Offence,Occurrence_Date,Occurrence_Year,Occurrence_Month,Occurrence_DayOfWeek,Occurrence_DayOfMonth,Occurrence_DayOfYear,Occurrence_Hour,...,Bike_Make,Bike_Model,Bike_Type,Bike_Speed,Bike_Colour,Cost_of_Bike,Status,ObjectId2,geometry,current_year
0,17744,GO-20179016397,THEFT UNDER,2017-10-03,2017,October,Tuesday,3,276,14,...,GI,ESCaPE 2,OT,7,BLK,700.0,STOLEN,1,"{'type': 'Point', 'coordinates': (-79.50655965...",2026
1,17759,GO-20172033056,THEFT UNDER - BICYCLE,2017-11-08,2017,November,Wednesday,8,312,3,...,UNKNOWN MAKE,NaN,TO,1,BLK,1100.0,RECOVERED,2,"{'type': 'Point', 'coordinates': (-79.50484874...",2026
2,17906,GO-20189030822,THEFT UNDER - BICYCLE,2018-09-14,2018,September,Friday,14,257,9,...,OT,CROSSTRaIL,MT,24,BLK,904.0,STOLEN,3,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
3,17962,GO-2015804467,THEFT UNDER,2015-05-07,2015,NaN,Thursday,7,127,18,...,GT,NaN,TO,10,BLKDGR,400.0,STOLEN,4,"{'type': 'Point', 'coordinates': (-79.51170915...",2026
4,17963,GO-20159002781,THEFT UNDER,2015-05-16,2015,NaN,Saturday,16,136,12,...,GI,NaN,MT,6,RED,600.0,STOLEN,5,"{'type': 'Point', 'coordinates': (-79.51132657...",2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25564,9361,GO-2015543181,MISCHIEF UNDER,2015-04-01,2015,NaN,Wednesday,1,91,17,...,UNKNOWN MAKE,BMX WILD MaN,RG,0,SIL,600.0,STOLEN,25565,"{'type': 'Point', 'coordinates': (-79.21555349...",2026
25565,11318,GO-20169004589,THEFT UNDER,2016-05-16,2016,NaN,Monday,16,137,21,...,SC,NaN,OT,14,NaN,900.0,STOLEN,25566,"{'type': 'Point', 'coordinates': (-79.21767046...",2026
25566,11462,GO-20169005434,THEFT UNDER,2016-06-04,2016,NaN,Saturday,4,156,22,...,SC,aNTRIM,MT,24,WHI,700.0,STOLEN,25567,"{'type': 'Point', 'coordinates': (-79.2360175,...",2026
25567,11695,GO-20161170896,THEFT UNDER,2016-07-04,2016,NaN,Monday,4,186,20,...,UNKNOWN MAKE,NaN,SC,1,NaN,3000.0,STOLEN,25568,"{'type': 'Point', 'coordinates': (-79.20060719...",2026
25568,11883,GO-20169007653,THEFT UNDER - BICYCLE,2016-07-22,2016,NaN,Friday,22,204,9,...,SU,aSCENT MOUNTaIN,MT,21,ONG,200.0,STOLEN,25569,"{'type': 'Point', 'coordinates': (-79.23734742...",2026

In [155]:
Model_Groups = df.groupby("Bike_Model")

In [156]:
Model_Groups["Bike_Make"].unique()

Bike_Model
#199-2763-0                  [SU]
&BaCK SaDDLEBaG              [GI]
'11 7.2 FX WSD               [TR]
'INTENSE""         [UNKNOWN MAKE]
'PIRaNHa'                    [GF]
                        ...
aXIS5                        [OT]
aXIa                         [NO]
aZ EBIKE           [UNKNOWN MAKE]
aa00302619                   [NO]
aa10851515                   [NO]
Name: Bike_Make, Length: 8097, dtype: object

In [157]:
df.to_csv("updated_df.csv")

In [158]:
pd.DataFrame({'A':[1,2],'B':[3,4]})

   A  B
0  1  3
1  2  4

# Exercise

In [160]:
df = pd.read_csv("python/05_src/data/slides_data/subway_stations.csv")
df

     stop_lat   stop_lon             station
0   43.666061 -79.411065    BATHURST STATION
1   43.670149 -79.390089         BAY STATION
2   43.766872 -79.386703     BAYVIEW STATION
3   43.769202 -79.376312   BESSARION STATION
4   43.670049 -79.385389       BLOOR STATION
..        ...        ...                 ...
72  43.734475 -79.450920      WILSON STATION
73  43.686440 -79.312471    WOODBINE STATION
74  43.670997 -79.385956       YONGE STATION
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

[77 rows x 3 columns]

In [161]:
df.head()

    stop_lat   stop_lon            station
0  43.666061 -79.411065   BATHURST STATION
1  43.670149 -79.390089        BAY STATION
2  43.766872 -79.386703    BAYVIEW STATION
3  43.769202 -79.376312  BESSARION STATION
4  43.670049 -79.385389      BLOOR STATION

In [162]:
df.tail(n=2)

     stop_lat   stop_lon             station
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

In [163]:
df.shape

(77, 3)

In [168]:
filtered_df = df.loc[df["station"].isin(["COLLEGE STATION", "ROYAL YORK STATION"])]

In [166]:
filtered_df.to_csv("exported_data.csv")